spring:
  thymeleaf:
    mode: LEGACYHTML5
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      max-lifetime: 30000
      idle-timeout: 30000
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
---
spring:
  profiles: dev
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/ecshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: yali
logging:
  level:
    com.wzh: debug
server:
  port: 80
---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: '&%1111'

server:
  port: 8088
