spring:
  thymeleaf:
    mode: LEGACYHTML5
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      max-lifetime: 30000
      idle-timeout: 30000
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
  redis:
    host: 192.168.1.8
    database: 0
    port: 6379
    password:
    timeout: 1s
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
---
spring:
  profiles: dev
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://192.168.1.8:3306/ecshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: 123456
logging:
  level:
    com.wzh: debug
server:
  port: 80
---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: '&%1111'

server:
  port: 8088
